version: "3.1"
services:
  postgresqldb:
    container_name: postgres-library
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library

  app:
    container_name: tomcat-library
    image: tomcat:10.1.8-jdk17
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./build/libs/library-0.1.war:/usr/local/tomcat/webapps/ROOT.war

  rabbitmq:
    container_name: 'library-rabbitmq'
    image: rabbitmq:3.10-management
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/

volumes:
  postgres-data: