version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongoDB-library
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db
volumes:
  mongodb_data_cont: