version: "3.1"

services:
  app:
    container_name: library
    image: eclipse-temurin:17-jdk-alpine
    build: .
    entrypoint: ["java","-jar","library-0.1.jar"]
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    networks:
      - datalink

  postgresqldb:
    image: postgres
    ports:
      - "54320:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - PGDATA=/var/lib/postgresql/data
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library
    networks:
      - datalink
    expose:
      - 5432
networks:
  datalink:
    driver: bridge
volumes:
  postgres-data: