version: "3.1"
services:
  postgresqldb:
    container_name: postgres-library
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=library
  mongo1:
    image: mongo:latest
    container_name: mongoDB-library
    hostname: mongo1
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_cont:/data/db
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongosetup:
    image: mongo:latest
    depends_on:
      - mongo1
    volumes:
      - ./scripts/rs-init.sh:/scripts/rs-init.sh
    restart: "no"
    entrypoint: [ "bash", "/scripts/rs-init.sh" ]

  app:
    container_name: tomcat-library
    image: tomcat:10.1.8-jdk17
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresqldb:5432/library
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    volumes:
      - ./build/libs/library-0.1.war:/usr/local/tomcat/webapps/ROOT.war
volumes:
  postgres-data:
  mongo_data_cont: